#!/usr/bin/env bash
# comment
#sudo apt-get update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
# This creates a new landing page for your sevrver.
echo "Hello World!" | sudo tee  /var/www/html/index.html
# to apply changes while its still running - reload
#sudo sed  -i '/server_name _;/a\\trewrite ^\/redirect_me  https:\/\/www.youtube.com permanent;' /etc/nginx/sites-enabled/default
new_string="server_name _;\n\tlocation /redirect_me {\n\t\trewrite ^\/redirect_me https:\/\/www.google.com permanent;\n\t}"
# finds s/server_name _; in default configuration and replace it with new string
sudo sed -i "s#server_name _;#$new_string#"  /etc/nginx/sites-enabled/default
sudo service nginx restart
